### ISSUE TITLE
No git access to repo

### ISSUE THREAD

**Issue by sc0ttj** [puppylinux-woof-CE/awesome-puppy-linux#1]
`git checkout -b initial-version`
 
... did some edits

```
git add .
git commit -m 'updated README'
git push --set-upstream origin intial-version
```
Gave me this error:

```
remote: Permission to puppylinux-woof-CE/awesome-puppy-linux.git denied to sc0ttj.
fatal: unable to access 'https://github.com/puppylinux-woof-CE/awesome-puppy-linux.git/': The requested URL returned error: 403
```

**Comment by 01micko** [comment]
I see you are invited as a collaborator if you choose to accept.

**Comment by wdlkmpx** [comment]
https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/inviting-collaborators-to-a-personal-repository

> 8. The user will receive an email inviting them to the repository. Once they accept your invitation, they will have collaborator access to your repository.

https://github.com/puppylinux-woof-CE/awesome-puppy-linux/invitations
https://github.com/puppylinux-woof-CE/Pkg/invitations

**Comment by sc0ttj** [comment]
Lovely .. done.. thanks .. (didn't get the email, think it went to my work one..)
