### ISSUE TITLE
Update all links to the new forum

### ISSUE THREAD

**Issue by sc0ttj** [puppylinux-woof-CE/awesome-puppy-linux#11]
https://forum.puppylinux.com/index.php

**Comment by peabee** [comment]
Seems to be duplicating a lot of stuff on the official webpages - do we have the spare effort needed to keep both up to date - I suspect not!
The ScPup line looks wrong - it should either be Slacko (which is 14.1 based) or should be Slackware Current - whichever there is a line missing as both Slacko and ScPup should be included.
pup-volume-monitor is worthy of inclusion.

**Comment by sc0ttj** [comment]
> Seems to be duplicating a lot of stuff on the official webpages - do we have the spare effort needed to keep both up to date - I suspect not!
Given that we only do "official" or "mainline" releases once a year or so, maybe twice, then I'd say "yes".. 

It can't end up more confusing, out of date and full of broken links than our wiki, can it?

 > The ScPup line looks wrong - it should either be Slacko (which is 14.1 based) or should be Slackware Current - whichever there is a line missing as both Slacko and ScPup should be included.
> pup-volume-monitor is worthy of inclusion.
Oky doke.

**Comment by sc0ttj** [comment]
@peabee where are these slack pups u refer to?

They are not listed with the names u describe on the homepage.. in fact, there are no slack 14.2 pups listed there at all!


http://puppylinux.com/    <-- scroll down to list of official releases .. that is what i copied... happy to fix it.. but dunno what pups you are even referring to, let alone their release dates or forum pages...

**Comment by peabee** [comment]
The only **Official** Slackware based pup is Slacko which is Slackware-**14.1** based

There is no **Official** 14.2 or Current pup

http://puppylinux.com/
Slackware 14.1	x86 32-bit	Slacko Puppy 6.3.2	Main - Mirror - Checksum
Slackware64 14.1	x86_64 64-bit	Slacko64 Puppy 6.3.2	Main - Mirror - Checksum

http://puppylinux.com/download.html
ScPup | SlackwareCurrent compatible Pup (32 & 64bit) | ScPup Forum Page
Slacko14.2 | Slackware14.2 compatible Pup (32 & 64bit) | Slacko14.2 Forum Page
Slacko14.1 | Slackware14.1 compatible Official Pup (32 & 64bit) | Slacko Website

**Comment by sc0ttj** [comment]
Gotcha, thanks :)
